### ISSUE TITLE
1.3 legacy docs - review tree.json & regenerate

### ISSUE THREAD

**Issue by lbod** [dojo/dapi#51]
It appears the tree.json is not correct. See http://dojotoolkit.org/api/?qs=1.3/dojox/grid/TreeSelection

dojox/grid/TreePath, dojox/grid/TreeGrid are the same

I'll need to run the php tools to regenerate again and compare

**Comment by wkeese** [comment]
Relatedly, if I select 1.3 in the dropdown and try to open dojo/Animation or dijit/Calendar, I get an error.

**Comment by lbod** [comment]
Looking back through our irc discussions I remember this now... This was added https://github.com/wkeese/dojo-api-data/commit/e6700fdeea48d6871080f695f7ded02c0bf799c4

So I need to figure out how this differs between https://github.com/wkeese/dojo-api-data and https://github.com/lbod/dojo-old-static-docs seeing as the current install script i.e. https://github.com/dojo/dapi/blob/master/dtk-install.sh pulls from https://github.com/lbod/dojo-site-api

Too many repo's :(

**Comment by lbod** [comment]
Ok, so my dtk install script clones from https://github.com/lbod/dojo-site-api.git and it looks like I didn't commit the tree.json fix for 1.3 in there, compared to the commit in https://github.com/wkeese/dojo-api-data
The dtk site (running via node) only needs the json data for 1.8 and up but needs the static docs and tree.json for legacy. So I think all I need to do is update https://github.com/lbod/dojo-site-api/blob/master/data/1.3/tree.json with the version I committed to your repo and all should be good. 

I have the static docs tarred up in that repo `legacyhtml.tar.gz` but I'm not sure how that ties up with https://github.com/dojo/dapi/issues/53 i.e. the rewrites, I think it probably doesn't matter as those rewrites were only for legacy, what do you think?

I'm not really interested in hosting a repo with ALL the statically generated docs for all versions, non legacy docs can be generated easily from dapi. So it depends on how important you see https://github.com/wkeese/dojo-api-data being used seeing as you thought it important for end users they could just get all the HTML and run themselves, personally I don't see the need for it.

**Comment by wkeese** [comment]
> I have the static docs tarred up in that repo legacyhtml.tar.gz but I'm not sure how that ties up with #53 i.e. the rewrites, I think it probably doesn't matter as those rewrites were only for legacy, what do you think?

AFAIK legacyhtml.tar.gz is unrelated to #53.

> I'm not really interested in hosting a repo with ALL the statically generated docs for all versions, non legacy docs can be generated easily from dapi.

OK, then just host what you like.  I'll probably keep https://github.com/wkeese/dojo-api-data around so people can access the static docs if they want to (without running spider.js).   I agree that it's simple to run spider.js, but OTOH I don't want to give people an excuse to complain about dojo.

**Comment by lbod** [comment]
closed as per https://github.com/lbod/dojo-site-api/commit/969b1b9269bc3f4a113bfc43b088e289113894c3
